<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/Membershipperiod/MembershipPeriodDetail.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:35c86c1b1ddac1ec06c370d3d1244e72)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_Membershipperiod_DAO_MembershipPeriodDetail constructor.
 */
class CRM_Membershipperiod_DAO_MembershipPeriodDetail extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_membership_period_detail';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique Membership Period Detail ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * FK to Membership
   *
   * @var int unsigned
   */
  public $membership_id;
  /**
   * Currency code e.g. USD
   *
   * @var text
   */
  public $currency_code;
  /**
   * FK to Contribution
   *
   * @var int unsigned
   */
  public $contribution_id;
  /**
   * FK to Membership Type
   *
   * @var int unsigned
   */
  public $membership_type_id;
  /**
   * Number of membership periods this membership commencement/renewal corresponds to
   *
   * @var int unsigned
   */
  public $number_of_periods;
  /**
   * Starting date of the related membership period(s)
   *
   * @var date
   */
  public $start_date;
  /**
   * Ending date of the related membership period(s)
   *
   * @var date
   */
  public $end_date;
  /**
   * Membership duration unit. E.g. day, week, month, year
   *
   * @var text
   */
  public $membership_duration_unit;
  /**
   * Membership duration interval. E.g. 1(year), 60(days)
   *
   * @var int unsigned
   */
  public $membership_duration_interval;
  /**
   * Timestamp of the operation
   *
   * @var timestamp
   */
  public $created_at;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_membership_period_detail';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'membership_id', 'civicrm_membership', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'contribution_id', 'civicrm_contribution', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'membership_type_id', 'civicrm_membership_type', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique Membership Period Detail ID',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
        ) ,
        'membership_id' => array(
          'name' => 'membership_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Membership',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
          'FKClassName' => 'CRM_Member_DAO_Membership',
        ) ,
        'currency_code' => array(
          'name' => 'currency_code',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Currency Code') ,
          'description' => 'Currency code e.g. USD',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
        ) ,
        'contribution_id' => array(
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Contribution',
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Contribution',
        ) ,
        'membership_type_id' => array(
          'name' => 'membership_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Membership Type',
          'required' => false,
          'default' => 'NULL',
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
          'FKClassName' => 'CRM_Member_DAO_MembershipType',
        ) ,
        'number_of_periods' => array(
          'name' => 'number_of_periods',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number Of Periods') ,
          'description' => 'Number of membership periods this membership commencement/renewal corresponds to',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
        ) ,
        'start_date' => array(
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Start Date') ,
          'description' => 'Starting date of the related membership period(s)',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
        ) ,
        'end_date' => array(
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('End Date') ,
          'description' => 'Ending date of the related membership period(s)',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
        ) ,
        'membership_duration_unit' => array(
          'name' => 'membership_duration_unit',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Membership Duration Unit') ,
          'description' => 'Membership duration unit. E.g. day, week, month, year',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
        ) ,
        'membership_duration_interval' => array(
          'name' => 'membership_duration_interval',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Membership Duration Interval') ,
          'description' => 'Membership duration interval. E.g. 1(year), 60(days)',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
        ) ,
        'created_at' => array(
          'name' => 'created_at',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Created At') ,
          'description' => 'Timestamp of the operation',
          'required' => true,
          'table_name' => 'civicrm_membership_period_detail',
          'entity' => 'MembershipPeriodDetail',
          'bao' => 'CRM_Membershipperiod_DAO_MembershipPeriodDetail',
          'localizable' => 0,
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'membership_period_detail', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'membership_period_detail', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array();
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
